"""Drop salt column from user table

Revision ID: 27d293e32aa8
Revises: c6442ec3d337
Create Date: 2024-10-27 23:45:16.227932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27d293e32aa8'
down_revision = 'c6442ec3d337'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('salt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salt', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
