"""Add price_per_hour to Room model

Revision ID: 7b167eafc009
Revises: ec1203d5ee4e
Create Date: 2024-10-31 19:10:31.210192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b167eafc009'
down_revision = 'ec1203d5ee4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_per_hour', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_column('price_per_hour')

    # ### end Alembic commands ###
