"""Add transaction_id to Payment model

Revision ID: e0d7d1898854
Revises: 7b167eafc009
Create Date: 2024-11-02 20:45:35.723210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0d7d1898854'
down_revision = '7b167eafc009'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('payments') as batch_op:
        batch_op.add_column(sa.Column('transaction_id', sa.String(), nullable=False))
        batch_op.create_unique_constraint('uq_transaction_id', ['transaction_id'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments') as batch_op:
        batch_op.drop_constraint('uq_transaction_id', 'payments', type_='unique')
        batch_op.drop_column('transaction_id')

    # ### end Alembic commands ###
